---
name: 'Push docker image'
description: 'Runs commit lint'
inputs:
  stop_at_commit_msg:
    description: |
      Validate until a commit whose message starts with this value is found
    required: true
    default: 'Merge pull request #'
  commit_msg_regex:
    description: Regex that prescribes the correct commit message syntax
    required: true
    default: ''
  project_specific_repo:
    description: |
      Whether the repo is project-specific or not. Commit regex defaults to
      <type>: #<ticket no> <commit msg> if project-specific, else it defaults
      to <type>(<project>): #<ticket no> <commit msg>
    required: true
    default: 'yes'
runs:
  using: 'node12'
  main: 'dist/index.js'
