---
name: 'Push docker image'
description: 'Runs commit lint'
inputs:
  stop_at_commit_msg:
    description: |
      Validate until a commit whose message starts with this value is found
    required: true
    default: 'Merge pull request #'
  commit_msg_regex:
    description: Regex that prescribes the correct commit message syntax
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
